apiVersion: apps/v1
kind: Deployment

metadata:
  name: ihdbserver

spec:
  replicas: 1
  
  selector:
    matchLabels:
      component: ihdbserver
  
  template:
    metadata:
      labels:
        component: ihdbserver
      
    spec:
      containers:
        - name: ihdbserver
          image: docker.io/mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb


  

