apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihapp-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: us.gcr.io/anthos-testing-271707/ihapp@sha256:ab25b71bc1b275664b8024088e7843a473accf4bfabca54b203b007dbcd2c9b6
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb
            - name: MYSQL_HOST
              value: ihdbserver

  selector:
    matchLabels:
      component: ihapp
