apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihapp-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: us.gcr.io/anthos-testing-271707/ihapp@sha256:50a1ad352d81c96c8cfdeb6f7859034b4bcfb0515935bdc9aa809bf24315a9ea
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb
            - name: MYSQL_HOST
              value: ihdbserver

  selector:
    matchLabels:
      component: ihapp
