apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihapp-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: us.gcr.io/anthos-testing-271707/ihapp@sha256:eea7b7d184d11940ffd036e345fafee1c3b1af85ab393e6df134b692ce900480
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb
            - name: MYSQL_HOST
              value: ihdbserver

  selector:
    matchLabels:
      component: ihapp
