apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihapp-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: us.gcr.io/anthos-testing-271707/ihapp@sha256:89fb67ccb11828143e416334b7120c0a33d178eeb545ab5779119fab1157cbeb
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb
            - name: MYSQL_HOST
              value: ihdbserver

  selector:
    matchLabels:
      component: ihapp
