apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihapp-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: us.gcr.io/anthos-testing-271707/ihapp@sha256:b21e9c398e7a004e1f96cccb790099ec26653ba27fdfbdff097bfcd62b71af1a
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: ihproddb
            - name: MYSQL_HOST
              value: ihdbserver

  selector:
    matchLabels:
      component: ihapp
