
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ihapp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sendtoashish/ihapp-application.git    
    targetRevision: HEAD
    path: indianhandicrafts/k8s/lab1-vanilla/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ihapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

