name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
        - name: Git Checkout Code
          uses: actions/checkout@v1
          id: git_checkout
        - name: Build Docker Image
#         id: buildAndPushImage
          uses: mr-smithers-excellent/docker-build-push@v5 
          with:
           image: sendtoashish123/ihapp
           tags: v1
           registry: docker.io
           dockerfile: indianhandicrafts/Dockerfile
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
        - uses: sigstore/cosign-installer@main

        - name: Write signing key to disk (only needed for `cosign sign --key`)
          run: echo "${{ secrets.COSIGN_SECRET }}" > cosign.key

        - name: Sign container image
          run: |
            cosign sign --key cosign.key \
            docker.io/sendtoashish123/ihapp:v1
  
