name:  Deploy to GKE with ARGOCD 
on:
  pull_request:
    types: [closed]
env:
  PROJECT_ID: ${{secrets.PROJECT_ID}} 
  GKE_CLUSTER_DEV: dev-cluster
  GKE_CLUSTER_TEST: test-cluster
  GKE_ZONE: us-central1-c  
jobs:
  validate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        with: 
         ref: ${{github.head_ref}}
        id: git_checkout
      - name: checking file 
        run: |
          cat indianhandicrafts/k8s/argocd/web-deployment.yaml
      - name: Set up Google Cloud Cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            service_account_key: ${{secrets.GOOGLE_KEY}}
            project_id: ${{secrets.PROJECT_ID}}
            export_default_credentials: true
      - name: Get GKE Credentials for dev cluster
        if: ${{github.ref == 'dev'}}
        run: |-
              gcloud container clusters get-credentials "$GKE_CLUSTER_DEV" --zone "$GKE_ZONE"
      - name: Get GKE Credentials for test cluster
        if: ${{github.ref == 'test'}}
        run: |
             gcloud container clusters get-credentials "$GKE_CLUSTER_TEST" --zone "$GKE_ZONE"
              
      - name: Deploy argocd on cluster 
        run: |-
             kubectl get namespace argocd || \
             kubectl create namespace argocd
             kubectl apply -n argocd -f install.yaml
             kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
             kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      - name: Deploy application
        run: |
             cat indianhandicrafts/argocd.yaml 
             kubectl apply -f indianhandicrafts/argocd.yaml 
