name: "Replicating DIGEST to deployment file"
on:
  schedule:
    - cron:  '*/5 * * * *'    # At every 15th minute

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered your original job 
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Create local changes
        run: |
          cp sample-dep.yaml indianhandicrafts/k8s/lab1-vanilla/web-deployment.yaml
      - name: Commit files
        run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add .
           git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.TOKEN }}
            branch: master
      # If job finished successfully, remove the workflow file (and tag if necessary)
   #   - name: Remove scheduled job
   #     uses: cardinalby/unschedule-job-action@v1
   #     with:
   #       ghToken: ${{ secrets.WORKFLOWS_TOKEN }}         
